Repository WishMarket/WishMarket-BE, pull requests merged in 2023-02, with the labels that each got.

#1 feat(common) : 공통 기능 작성
  build.gradle
  src/main/java/com/zerobase/wishmarket/WishMarketApplication.java
  src/main/java/com/zerobase/wishmarket/config/SwaggerConfig.java
  src/main/java/com/zerobase/wishmarket/entity/BaseEntity.java
  src/main/java/com/zerobase/wishmarket/exception/ErrorCode.java
  src/main/java/com/zerobase/wishmarket/exception/ErrorResponse.java
  src/main/java/com/zerobase/wishmarket/exception/ErrorResult.java
  src/main/java/com/zerobase/wishmarket/exception/GlobalException.java
  src/main/java/com/zerobase/wishmarket/exception/GlobalExceptionHandler.java
  src/main/java/com/zerobase/withmarket/WithMarketApplication.java
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
  src/test/java/com/zerobase/wishmarket/WithMarketApplicationTests.java
Labels: ✨ Feature

#4 feat(product): product 패키지 생성 및 엔티티, 예외처리 정의
  build.gradle
  src/main/java/com/zerobase/wishmarket/domain/product/controller/ProductController.java
  src/main/java/com/zerobase/wishmarket/domain/product/exception/ProductErrorCode.java
  src/main/java/com/zerobase/wishmarket/domain/product/exception/ProductException.java
  src/main/java/com/zerobase/wishmarket/domain/product/exception/ProductNotFoundException.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/ProductEntity.java
  src/main/java/com/zerobase/wishmarket/domain/product/repository/ProductRepository.java
  src/main/java/com/zerobase/wishmarket/domain/product/service/ProductService.java
  src/test/java/com/zerobase/wishmarket/domain/product/exception/ProductErrorCodeTest.java
Labels: ✅ Test, ⚙ Setting, ✨ Feature

#6 feat(user, delivery) : 회원 공통 작업을 위한 기본 설정
  src/main/java/com/zerobase/wishmarket/domain/user/model/entity/DeliveryAddress.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/entity/UserEntity.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/type/UserRegistration.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/type/UserRoles.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/type/UserStatus.java
  src/main/java/com/zerobase/wishmarket/domain/user/repository/DeliveryAddressRepository.java
  src/main/java/com/zerobase/wishmarket/domain/user/repository/UserRepository.java
Labels: ⚙ Setting, ✨ Feature

#9 fix(common) : Error 응답 시 HttpStatus가 응답되도록 수정
  src/main/java/com/zerobase/wishmarket/domain/product/exception/ProductErrorCode.java
  src/main/java/com/zerobase/wishmarket/domain/product/exception/ProductException.java
  src/main/java/com/zerobase/wishmarket/exception/ErrorCode.java
  src/main/java/com/zerobase/wishmarket/exception/ErrorResponse.java
  src/main/java/com/zerobase/wishmarket/exception/GlobalExceptionHandler.java
Labels: 🐞 BugFix

#12 feat(auth) : 인증 코드 메일 전송 및 인증 코드 검증 API
  build.gradle
  src/main/java/com/zerobase/wishmarket/client/RedisClient.java
  src/main/java/com/zerobase/wishmarket/config/RedisConfig.java
  src/main/java/com/zerobase/wishmarket/domain/auth/components/MailComponents.java
  src/main/java/com/zerobase/wishmarket/domain/auth/controller/AuthController.java
  src/main/java/com/zerobase/wishmarket/domain/auth/exception/AuthErrorCode.java
  src/main/java/com/zerobase/wishmarket/domain/auth/exception/AuthException.java
  src/main/java/com/zerobase/wishmarket/domain/auth/model/dto/AuthCodeMailForm.java
  src/main/java/com/zerobase/wishmarket/domain/auth/model/dto/AuthCodeVerifyForm.java
  src/main/java/com/zerobase/wishmarket/domain/auth/service/AuthService.java
  src/main/java/com/zerobase/wishmarket/exception/CommonErrorCode.java
  src/main/java/com/zerobase/wishmarket/exception/GlobalException.java
  src/main/resources/static/mailTemplate/AuthCodeMail.html
Labels: ✨ Feature

#16 feat(User) : google login 구현
  build.gradle
  src/main/java/com/zerobase/wishmarket/config/SecurityConfig.java
  src/main/java/com/zerobase/wishmarket/domain/user/controller/AuthController.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/OAuthUserInfo.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/entity/UserEntity.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/type/OAuthAttributes.java
  src/main/java/com/zerobase/wishmarket/domain/user/repository/UserRepository.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/OAuthService.java
  src/main/resources/application.properties
  src/test/java/com/zerobase/wishmarket/domain/auth/OAuthLoginTest.java
Labels: ✨ Feature

#20 feat(User) : naver 로그인 구현
  src/main/java/com/zerobase/wishmarket/domain/user/config/LoginUserArgumentResolver.java
  src/main/java/com/zerobase/wishmarket/domain/user/config/LoginUserInfo.java
  src/main/java/com/zerobase/wishmarket/domain/user/config/WebConfig.java
  src/main/java/com/zerobase/wishmarket/domain/user/controller/UserController.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/type/OAuthAttributes.java
Labels: ✨ Feature

#32 setting : gitIgnore, properties 수정
  .gitignore
  src/main/resources/application.properties
Labels: 📃 Docs

#21 feat(User) : 이메일을 이용한 회원 가입 API
  build.gradle
  src/main/java/com/zerobase/wishmarket/config/SecurityConfig.java
  src/main/java/com/zerobase/wishmarket/domain/user/controller/UserController.java
  src/main/java/com/zerobase/wishmarket/domain/user/exception/UserErrorCode.java
  src/main/java/com/zerobase/wishmarket/domain/user/exception/UserException.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/SignUpEmailDto.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/SignUpForm.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/entity/UserEntity.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/type/UserRegistrationType.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/type/UserRolesType.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/type/UserStatusType.java
  src/main/java/com/zerobase/wishmarket/domain/user/repository/UserRepository.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/UserSignUpService.java
  src/test/java/com/zerobase/wishmarket/domain/user/service/UserSignUpServiceTest.java
Labels: ✅ Test, ✨ Feature

#35 fix : 회원 기능 충돌 해결 및 패키지 구조 변경
  src/main/java/com/zerobase/wishmarket/common/redis/RedisClient.java
  src/main/java/com/zerobase/wishmarket/config/SecurityConfig.java
  src/main/java/com/zerobase/wishmarket/domain/authcode/components/MailComponents.java
  src/main/java/com/zerobase/wishmarket/domain/authcode/controller/AuthCodeController.java
  src/main/java/com/zerobase/wishmarket/domain/authcode/exception/AuthErrorCode.java
  src/main/java/com/zerobase/wishmarket/domain/authcode/exception/AuthException.java
  src/main/java/com/zerobase/wishmarket/domain/authcode/model/constants/AuthCodeProperties.java
  src/main/java/com/zerobase/wishmarket/domain/authcode/model/dto/AuthCodeMailForm.java
  src/main/java/com/zerobase/wishmarket/domain/authcode/model/dto/AuthCodeVerifyForm.java
  src/main/java/com/zerobase/wishmarket/domain/authcode/service/AuthCodeService.java
  src/main/java/com/zerobase/wishmarket/domain/user/annotation/LoginUserInfo.java
  src/main/java/com/zerobase/wishmarket/domain/user/components/LoginUserArgumentResolver.java
  src/main/java/com/zerobase/wishmarket/domain/user/config/WebConfig.java
  src/main/java/com/zerobase/wishmarket/domain/user/controller/UserAuthController.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/OAuthAttributes.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/entity/UserEntity.java
  src/main/java/com/zerobase/wishmarket/domain/user/repository/UserAuthRepository.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/OAuthService.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/UserAuthService.java
  src/test/java/com/zerobase/wishmarket/domain/auth/OAuthLoginTest.java
  src/test/java/com/zerobase/wishmarket/domain/user/service/UserSignUpServiceTest.java
Labels: 🐞 BugFix

#28 deploy(S3) : S3 - Spring 연동 및 Controller 단에서 업로드 테스트
  build.gradle
  src/main/java/com/zerobase/withmarket/config/AwsS3Config.java
  src/main/java/com/zerobase/withmarket/s3_test_controller/S3TestFileController.java
Labels: 🌏 Deploy, ✨ Feature

#30 feat(Product) : 카테고리별 상품 리스트 조회 및 베스트 상품 리스트 조회
  build.gradle
  src/main/java/com/zerobase/wishmarket/WishMarketApplication.java
  src/main/java/com/zerobase/wishmarket/config/BatchJob.java
  src/main/java/com/zerobase/wishmarket/config/BatchScheduler.java
  src/main/java/com/zerobase/wishmarket/domain/product/Images/IT_DEVICE/상품 이미지 파일
  src/main/java/com/zerobase/wishmarket/domain/product/controller/ProductController.java
  src/main/java/com/zerobase/wishmarket/domain/product/exception/ProductErrorCode.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/ProductInputForm.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/entity/Best.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/entity/Product.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/entity/RedisBestProducts.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/entity/Review.java
  src/main/java/com/zerobase/wishmarket/domain/product/repository/BestRepository.java
  src/main/java/com/zerobase/wishmarket/domain/product/repository/ProductRepository.java
  src/main/java/com/zerobase/wishmarket/domain/product/repository/RedisBestRepository.java
  src/main/java/com/zerobase/wishmarket/domain/product/service/ProductService.java
  src/test/java/com/zerobase/wishmarket/domain/product/service/ProductServiceTest.java
Labels: ✨ Feature

#41 feat : S3 이미지 업로드 및 삭제 Util
  src/main/java/com/zerobase/wishmarket/common/util/S3Util.java
  src/main/java/com/zerobase/wishmarket/config/AwsS3Config.java
  src/main/java/com/zerobase/wishmarket/exception/CommonErrorCode.java
  src/main/java/com/zerobase/wishmarket/exception/GlobalExceptionHandler.java
  src/main/java/com/zerobase/withmarket/s3_test_controller/S3TestFileController.java
Labels: ✨ Feature

#45 fix(User) : OAuth2 로그인 유저 정보 활용 방법 수정 (Session->JWT)
  src/main/java/com/zerobase/wishmarket/domain/user/controller/UserAuthController.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/OAuthService.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/UserAuthService.java
Labels: 🐞 BugFix

#34 feat(Product) : Product detail 및 review 조회
  src/main/java/com/zerobase/wishmarket/domain/product/controller/ProductController.java
  src/main/java/com/zerobase/wishmarket/domain/product/controller/ReviewController.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/dto/ProductDetailDto.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/entity/Review.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/type/ProductCategory.java
  src/main/java/com/zerobase/wishmarket/domain/product/repository/ReviewRepository.java
  src/main/java/com/zerobase/wishmarket/domain/product/service/ProductService.java
  src/main/java/com/zerobase/wishmarket/domain/product/service/ReviewService.java
  src/main/java/com/zerobase/wishmarket/domain/user/controller/UserAuthController.java
  src/test/java/com/zerobase/wishmarket/domain/auth/OAuthLoginTest.java
  src/test/java/com/zerobase/wishmarket/domain/product/service/ProductServiceTest.java
  src/test/java/com/zerobase/wishmarket/domain/product/service/ReviewServiceTest.java
Labels: ✨ Feature

#52 fix(deploy) : dev 배포를 위한 코드 수정 1차
  build.gradle
  src/main/java/com/zerobase/wishmarket/common/jwt/JwtAuthenticationProvider.java
  src/main/java/com/zerobase/wishmarket/common/jwt/model/constants/JwtConstants.java
  src/main/java/com/zerobase/wishmarket/config/SecurityConfig.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/SignInResponse.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/UserAuthService.java
  src/test/java/com/zerobase/wishmarket/domain/auth/OAuthLoginTest.java
Labels: 🌏 Deploy, 🐞 BugFix

#47 fix(User) : 회원 가입 시 UserStatus 활동 상태로 변경
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/SignUpEmailResponse.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/entity/UserEntity.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/UserAuthService.java
Labels: 🐞 BugFix

#57 fix : static 파일 not found error 수정
  src/main/java/com/zerobase/wishmarket/domain/authcode/components/MailComponents.java
  src/main/java/com/zerobase/wishmarket/domain/authcode/controller/AuthCodeController.java
  src/main/java/com/zerobase/wishmarket/domain/authcode/service/AuthCodeService.java
Labels: 🐞 BugFix

#43 feat(product) : 상품검색기능 구현
  src/main/java/com/zerobase/wishmarket/domain/product/controller/ProductController.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/dto/ProductSearchDto.java
  src/main/java/com/zerobase/wishmarket/domain/product/repository/ProductRepository.java
  src/main/java/com/zerobase/wishmarket/domain/product/service/ProductService.java
  src/test/java/com/zerobase/wishmarket/domain/product/service/ProductServiceTest.java
Labels: ✨ Feature

#44 fix(product): 베스트 상품 조회와 카테고리별 상품 검색 수정
  src/main/java/com/zerobase/wishmarket/domain/product/controller/ProductController.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/dto/ProductBestDto.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/dto/ProductCategoryDto.java
  src/main/java/com/zerobase/wishmarket/domain/product/repository/ProductRepository.java
  src/main/java/com/zerobase/wishmarket/domain/product/service/ProductService.java
  src/test/java/com/zerobase/wishmarket/domain/product/service/ProductServiceTest.java
  src/test/java/com/zerobase/wishmarket/domain/product/service/ProductServiceTest_best_category.java
Labels: 🐞 BugFix

#60 feat(User) : 비밀번호 변경 기능 구현
  src/main/java/com/zerobase/wishmarket/domain/user/controller/UserController.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/ChangePwdForm.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/UserDto.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/entity/UserEntity.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/type/UserPasswordChangeReturnType.java
  src/main/java/com/zerobase/wishmarket/domain/user/repository/UserRepository.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/UserService.java
  src/test/java/com/zerobase/wishmarket/domain/user/service/UserServiceTest.java
Labels: ✨ Feature

#68 fix(Product): 상품관련 API merge과정에서 코드 충돌이 일어나 수정
  src/main/java/com/zerobase/wishmarket/domain/product/controller/ProductController.java
  src/main/java/com/zerobase/wishmarket/domain/product/repository/ProductRepository.java
  src/main/java/com/zerobase/wishmarket/domain/product/service/ProductService.java
  src/test/java/com/zerobase/wishmarket/domain/product/service/ProductServiceTest.java
  src/test/java/com/zerobase/wishmarket/domain/product/service/ProductServiceTest_best_category.java
Labels: 🐞 BugFix

#58 feat(Point): Point 사용 및 충전 기능구현 & 테스트코드 작성
  src/main/java/com/zerobase/wishmarket/domain/point/controller/PointController.java
  src/main/java/com/zerobase/wishmarket/domain/point/exception/PointErrorCode.java
  src/main/java/com/zerobase/wishmarket/domain/point/exception/PointException.java
  src/main/java/com/zerobase/wishmarket/domain/point/model/PointResponseDto.java
  src/main/java/com/zerobase/wishmarket/domain/point/service/PointService.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/entity/UserEntity.java
  src/test/java/com/zerobase/wishmarket/domain/point/service/PointServiceTest.java
Labels: ✨ Feature

#65 feat(User) : 회원정보 조회기능 기능 구현
  src/main/java/com/zerobase/wishmarket/domain/user/controller/UserController.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/UserDto.java
  src/main/java/com/zerobase/wishmarket/domain/user/repository/UserRepository.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/UserService.java
  src/test/java/com/zerobase/wishmarket/domain/user/service/UserServiceTest.java
Labels: ✨ Feature

#59 feat(User) : 로그아웃 기능 구현
  src/main/java/com/zerobase/wishmarket/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/zerobase/wishmarket/common/jwt/JwtAuthenticationProvider.java
  src/main/java/com/zerobase/wishmarket/domain/user/controller/UserAuthController.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/UserAuthService.java
Labels: ✨ Feature

#69 fix(UserAuth) : 사용자 인증 절차 수정
  src/main/java/com/zerobase/wishmarket/common/redis/RedisClient.java
  src/main/java/com/zerobase/wishmarket/config/SecurityConfig.java
  src/main/java/com/zerobase/wishmarket/domain/authcode/controller/AuthCodeController.java
  src/main/java/com/zerobase/wishmarket/domain/authcode/model/constants/AuthCodeProperties.java
  src/main/java/com/zerobase/wishmarket/domain/authcode/model/dto/AuthCodeResponse.java
  src/main/java/com/zerobase/wishmarket/domain/authcode/service/AuthCodeService.java
  src/main/java/com/zerobase/wishmarket/domain/user/controller/UserAuthController.java
  src/main/java/com/zerobase/wishmarket/domain/user/exception/UserErrorCode.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/EmailCheckForm.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/EmailCheckResponse.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/UserAuthService.java
  src/main/java/com/zerobase/wishmarket/exception/CommonErrorCode.java
Labels: 🐞 BugFix, ✨ Feature

#75 feat(Funding): 펀딩 API - 기본구성 요소 생성
  src/main/java/com/zerobase/wishmarket/domain/funding/controller/FundingController.java
  src/main/java/com/zerobase/wishmarket/domain/funding/exception/FundingErrorCode.java
  src/main/java/com/zerobase/wishmarket/domain/funding/exception/FundingException.java
  src/main/java/com/zerobase/wishmarket/domain/funding/model/entity/Funding.java
  src/main/java/com/zerobase/wishmarket/domain/funding/model/type/FundedStatusType.java
  src/main/java/com/zerobase/wishmarket/domain/funding/model/type/FundingStatusType.java
  src/main/java/com/zerobase/wishmarket/domain/funding/repository/FundingRepository.java
  src/main/java/com/zerobase/wishmarket/domain/funding/service/FundingService.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/entity/UserEntity.java
Labels: ✨ Feature

#80 fix(Auth) : 회원 가입 절차 수정
  src/main/java/com/zerobase/wishmarket/domain/authcode/model/constants/AuthCodeProperties.java
  src/main/java/com/zerobase/wishmarket/domain/authcode/model/dto/AuthCodeResponse.java
  src/main/java/com/zerobase/wishmarket/domain/authcode/service/AuthCodeService.java
  src/main/java/com/zerobase/wishmarket/domain/user/controller/UserAuthController.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/SignUpForm.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/UserAuthService.java
Labels: 🐞 BugFix

#82 feat : Jwt filter logout and reissue
  src/main/java/com/zerobase/wishmarket/common/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/zerobase/wishmarket/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/zerobase/wishmarket/common/jwt/JwtAuthenticationProvider.java
  src/main/java/com/zerobase/wishmarket/common/jwt/model/constants/JwtConstants.java
  src/main/java/com/zerobase/wishmarket/common/redis/RedisClient.java
  src/main/java/com/zerobase/wishmarket/config/SecurityConfig.java
  src/main/java/com/zerobase/wishmarket/domain/user/controller/UserAuthController.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/RefreshForm.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/ReissueResponse.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/entity/DeliveryAddress.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/UserAuthService.java
  src/main/java/com/zerobase/wishmarket/exception/CommonErrorCode.java
Labels: ✨ Feature

#83 fix(Product) : Detail & Review 수정
  src/main/java/com/zerobase/wishmarket/domain/product/controller/ProductController.java
  src/main/java/com/zerobase/wishmarket/domain/product/controller/ReviewController.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/dto/ProductDetailDto.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/dto/ReviewDto.java
  src/main/java/com/zerobase/wishmarket/domain/product/service/ReviewService.java
  src/test/java/com/zerobase/wishmarket/domain/product/service/ReviewServiceTest.java
Labels: 🐞 BugFix

#89 fix : 비밀번호 찾기 메일 전송 수정
  src/main/java/com/zerobase/wishmarket/domain/authcode/model/dto/AuthCodeMailForm.java
  src/main/java/com/zerobase/wishmarket/domain/authcode/service/AuthCodeService.java
Labels: 🐞 BugFix

#76 feature(Funding): 펀딩 API - 펀딩 시작하기
  src/main/java/com/zerobase/wishmarket/domain/funding/controller/FundingController.java
  src/main/java/com/zerobase/wishmarket/domain/funding/exception/FundingErrorCode.java
  src/main/java/com/zerobase/wishmarket/domain/funding/exception/FundingException.java
  src/main/java/com/zerobase/wishmarket/domain/funding/model/dto/FundingStartDto.java
  src/main/java/com/zerobase/wishmarket/domain/funding/model/form/FundingStartInputForm.java
  src/main/java/com/zerobase/wishmarket/domain/funding/service/FundingService.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/ProductInputForm.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/dto/ProductBestDto.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/dto/ProductCategoryDto.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/dto/ProductDetailDto.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/dto/ProductSearchDto.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/entity/Product.java
  src/main/java/com/zerobase/wishmarket/domain/product/service/ProductService.java
  src/test/java/com/zerobase/wishmarket/domain/funding/service/FundingServiceTest.java
  src/test/java/com/zerobase/wishmarket/domain/product/service/ProductServiceTest.java
Labels: ✨ Feature

#73 fix(User) : OAuth Login User 수정
  src/main/java/com/zerobase/wishmarket/domain/user/controller/UserAuthController.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/OAuthAttributes.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/OAuthService.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/UserAuthService.java
Labels: 🐞 BugFix

#77 fix(User) : 회원정보 수정기능 구현(#66)
  src/main/java/com/zerobase/wishmarket/domain/user/controller/UserController.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/UpdateForm.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/UserDto.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/entity/DeliveryAddress.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/entity/UserEntity.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/UserService.java
  src/test/java/com/zerobase/wishmarket/domain/user/service/UserServiceTest.java
Labels: ✨ Feature

#90 feat(User) : 회원탈퇴 기능 구현(#23)
  src/main/java/com/zerobase/wishmarket/domain/user/controller/UserAuthController.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/type/UserWithdrawalReturnType.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/UserAuthService.java
Labels: ✨ Feature

#98 fix : 회원 가입 시 포인트 0원 수정 및 로그아웃 controller 단 return 추가
  src/main/java/com/zerobase/wishmarket/domain/user/controller/UserAuthController.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/entity/UserEntity.java
Labels: 🐞 BugFix

#100 feat(Funding) : 편딩 받기 API
  src/main/java/com/zerobase/wishmarket/domain/funding/controller/FundingController.java
  src/main/java/com/zerobase/wishmarket/domain/funding/exception/FundingErrorCode.java
  src/main/java/com/zerobase/wishmarket/domain/funding/model/entity/Funding.java
  src/main/java/com/zerobase/wishmarket/domain/funding/model/entity/Order.java
  src/main/java/com/zerobase/wishmarket/domain/funding/model/form/FundingReceptionForm.java
  src/main/java/com/zerobase/wishmarket/domain/funding/model/type/FundedStatusType.java
  src/main/java/com/zerobase/wishmarket/domain/funding/repository/OrderRepository.java
  src/main/java/com/zerobase/wishmarket/domain/funding/service/FundingService.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/entity/Product.java
  src/main/java/com/zerobase/wishmarket/domain/product/model/entity/ProductLikes.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/entity/DeliveryAddress.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/entity/UserEntity.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/UserAuthService.java
  src/test/java/com/zerobase/wishmarket/domain/funding/service/FundingServiceTest.java
Labels: ✨ Feature

#92 feat(Funding): 펀딩 참여하기 및 펀딩 리펙토링
  src/main/java/com/zerobase/wishmarket/domain/funding/controller/FundingController.java
  src/main/java/com/zerobase/wishmarket/domain/funding/exception/FundingErrorCode.java
  src/main/java/com/zerobase/wishmarket/domain/funding/model/dto/FundingJoinResponse.java
  src/main/java/com/zerobase/wishmarket/domain/funding/model/dto/FundingStartDto.java
  src/main/java/com/zerobase/wishmarket/domain/funding/model/dto/FundingStartResponse.java
  src/main/java/com/zerobase/wishmarket/domain/funding/model/entity/Funding.java
  src/main/java/com/zerobase/wishmarket/domain/funding/model/entity/FundingParticipation.java
  src/main/java/com/zerobase/wishmarket/domain/funding/model/type/FundedStatusType.java
  src/main/java/com/zerobase/wishmarket/domain/funding/repository/FundingParticipationRepository.java
  src/main/java/com/zerobase/wishmarket/domain/funding/service/FundingService.java
  src/test/java/com/zerobase/wishmarket/domain/funding/service/FundingJoinTest.java
  src/test/java/com/zerobase/wishmarket/domain/funding/service/FundingServiceTest.java
Labels: ✨ Feature

#95 feat(User) : 주소 클래스 수정
  src/main/java/com/zerobase/wishmarket/domain/user/controller/UserAuthController.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/UpdateForm.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/UserDto.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/entity/DeliveryAddress.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/entity/UserEntity.java
  src/main/java/com/zerobase/wishmarket/domain/user/repository/DeliveryAddressRepository.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/UserService.java
Labels: 🐞 BugFix

#103 fix(User) : 유저 검색 param 변경
  src/main/java/com/zerobase/wishmarket/domain/follow/controller/FollowController.java
  src/main/java/com/zerobase/wishmarket/domain/follow/service/FollowService.java
Labels: 🐞 BugFix

#104 feat(WishList): 펀딩 내역 (내가 친구들한테 줌)
  src/main/java/com/zerobase/wishmarket/domain/funding/controller/FundingController.java
  src/main/java/com/zerobase/wishmarket/domain/funding/model/dto/FundingListGiveResponse.java
  src/main/java/com/zerobase/wishmarket/domain/funding/repository/FundingParticipationRepository.java
  src/main/java/com/zerobase/wishmarket/domain/funding/service/FundingService.java
Labels: ✨ Feature

#67 feat(Alarm) : 알람기능 구현 및 테스트
  src/main/java/com/zerobase/wishmarket/WishMarketApplication.java
  src/main/java/com/zerobase/wishmarket/config/RedisConfig.java
  src/main/java/com/zerobase/wishmarket/domain/alarm/controller/AlarmController.java
  src/main/java/com/zerobase/wishmarket/domain/alarm/exception/AlarmErrorCode.java
  src/main/java/com/zerobase/wishmarket/domain/alarm/exception/AlarmException.java
  src/main/java/com/zerobase/wishmarket/domain/alarm/model/Alarm.java
  src/main/java/com/zerobase/wishmarket/domain/alarm/model/dto/AlarmResponseDto.java
  src/main/java/com/zerobase/wishmarket/domain/alarm/repository/AlarmRepository.java
  src/main/java/com/zerobase/wishmarket/domain/alarm/service/AlarmService.java
  src/main/java/com/zerobase/wishmarket/entity/BaseEntity.java
  src/test/java/com/zerobase/wishmarket/domain/alarm/service/AlarmServiceTest.java
Labels: ✨ Feature

#106 fix(User) : 회원탈퇴 로직 수정
  src/main/java/com/zerobase/wishmarket/domain/funding/model/entity/Funding.java
  src/main/java/com/zerobase/wishmarket/domain/user/controller/UserAuthController.java
  src/main/java/com/zerobase/wishmarket/domain/user/exception/UserErrorCode.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/entity/UserEntity.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/UserAuthService.java
Labels: 🐞 BugFix

#111 feat(Alarm) : 펀딩 시작,성공,실패 Alarm 기능 추가
  src/main/java/com/zerobase/wishmarket/domain/alarm/model/Alarm.java
  src/main/java/com/zerobase/wishmarket/domain/alarm/service/AlarmService.java
  src/main/java/com/zerobase/wishmarket/domain/funding/service/FundingService.java
  src/test/java/com/zerobase/wishmarket/domain/alarm/service/AlarmServiceTest.java
Labels: ✨ Feature

#109 fix(Funding): 펀딩 내역 (내가 친구들한테 줌)
  src/main/java/com/zerobase/wishmarket/domain/funding/controller/FundingController.java
  src/main/java/com/zerobase/wishmarket/domain/funding/model/dto/FundingListGiveResponse.java
  src/main/java/com/zerobase/wishmarket/domain/funding/service/FundingService.java
  src/test/java/com/zerobase/wishmarket/domain/funding/service/FundingServiceTest.java
Labels: 🐞 BugFix

#113 feat(Funding) : 내가 받은 펀딩 내역 API
  src/main/java/com/zerobase/wishmarket/domain/funding/controller/FundingController.java
  src/main/java/com/zerobase/wishmarket/domain/funding/model/dto/FundingMyGiftListResponse.java
  src/main/java/com/zerobase/wishmarket/domain/funding/repository/FundingParticipationRepository.java
  src/main/java/com/zerobase/wishmarket/domain/funding/repository/FundingRepository.java
  src/main/java/com/zerobase/wishmarket/domain/funding/service/FundingService.java
  src/main/java/com/zerobase/wishmarket/domain/product/repository/ReviewRepository.java
Labels: ✨ Feature

#116 fix(WishList): 찜목록이 없는 경우도 존재하지만, 찜목록이 없으면 null exception을 반환하는 경우
  src/main/java/com/zerobase/wishmarket/domain/wishList/service/WishListService.java
Labels: 🐞 BugFix

#117 fix(Funding): 펀딩에 중복참여가 가능하도록 수정 및 버그 수정
  src/main/java/com/zerobase/wishmarket/domain/funding/model/dto/FundingListGiveResponse.java
  src/main/java/com/zerobase/wishmarket/domain/funding/model/entity/FundingParticipation.java
  src/main/java/com/zerobase/wishmarket/domain/funding/repository/FundingParticipationRepository.java
  src/main/java/com/zerobase/wishmarket/domain/funding/service/FundingService.java
  src/test/java/com/zerobase/wishmarket/domain/funding/service/FundingJoinTest.java
  src/test/java/com/zerobase/wishmarket/domain/funding/service/FundingServiceTest.java
  src/test/java/com/zerobase/wishmarket/domain/product/service/ProductAddServiceTest.java
Labels: 🐞 BugFix

#119 fix(Follow) : 친구 페이징 수정
  src/main/java/com/zerobase/wishmarket/domain/follow/controller/FollowController.java
  src/main/java/com/zerobase/wishmarket/domain/follow/repository/FollowQueryRepository.java
  src/main/java/com/zerobase/wishmarket/domain/follow/service/FollowService.java
Labels: 🐞 BugFix

#124 feat(Follow) : 유명 인플루언서 목록 조회 API
  src/main/java/com/zerobase/wishmarket/domain/follow/controller/FollowController.java
  src/main/java/com/zerobase/wishmarket/domain/follow/service/FollowService.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/InfluencerResponse.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/entity/UserEntity.java
  src/main/java/com/zerobase/wishmarket/domain/user/repository/UserAuthRepository.java
Labels: ✨ Feature

#125 fix(User) : 회원정보 조회 수정
  src/main/java/com/zerobase/wishmarket/domain/user/controller/UserController.java
  src/main/java/com/zerobase/wishmarket/domain/user/model/dto/UserInfoResponse.java
  src/main/java/com/zerobase/wishmarket/domain/user/service/UserService.java
Labels: 🐞 BugFix

#127 feat(Funding): 펀딩 상세 조회
  src/main/java/com/zerobase/wishmarket/domain/funding/controller/FundingController.java
  src/main/java/com/zerobase/wishmarket/domain/funding/model/dto/FundingDetailResponse.java
  src/main/java/com/zerobase/wishmarket/domain/funding/service/FundingService.java
Labels: ✨ Feature
